### ISSUE TITLE
Error when Launching Multi-Agent System: With Docker

### ISSUE THREAD

**Issue by pinyaras** [run-llama/llama_deploy#120]
When trying to run `docker-compose up --build` got the following error from **human_consumer_1** and  **registration_task_1**.

> uman_consumer_1     | Process SpawnProcess-1:
> human_consumer_1     | Traceback (most recent call last):
> human_consumer_1     |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
> human_consumer_1     |     self.run()
> human_consumer_1     |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
> human_consumer_1     |     self._target(*self._args, **self._kwargs)
> human_consumer_1     |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
> human_consumer_1     |     target(sockets=sockets)
> human_consumer_1     |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
> human_consumer_1     |     return asyncio.run(self.serve(sockets=sockets))
> human_consumer_1     |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
> human_consumer_1     |     return loop.run_until_complete(main)
> human_consumer_1     |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
> human_consumer_1     |     return future.result()
> human_consumer_1     |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
> human_consumer_1     |     await self._serve(sockets)
> human_consumer_1     |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
> human_consumer_1     |     config.load()
> human_consumer_1     |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
> human_consumer_1     |     self.loaded_app = import_from_string(self.app)
> human_consumer_1     |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
> human_consumer_1     |     module = importlib.import_module(module_str)
> human_consumer_1     |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
> human_consumer_1     |     return _bootstrap._gcd_import(name[level:], package, level)
> human_consumer_1     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
> human_consumer_1     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
> human_consumer_1     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
> human_consumer_1     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
> human_consumer_1     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
> human_consumer_1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> human_consumer_1     |   File "/app/multi_agent_app/additional_services/human_consumer.py", line 6, in <module>
> human_consumer_1     |     from multi_agent_app.additional_services.task_result import TaskResultService
> human_consumer_1     |   File "/app/multi_agent_app/additional_services/task_result.py", line 10, in <module>
> human_consumer_1     |     from llama_agents.message_consumers.base import (
> human_consumer_1     | ImportError: cannot import name 'StartConsumingCallable' from 'llama_agents.message_consumers.base' (/app/.venv/lib/python3.10/site-packages/llama_agents/message_consumers/base.py)
> secret_agent_1       | 2024-07-09 20:05:50,671 - INFO - Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
> secret_agent_1       | 2024-07-09 20:05:50,671 - INFO - Started reloader process [1] using WatchFiles
> secret_agent_1       | 2024-07-09 20:05:55,510 - INFO - Started server process [8]
> secret_agent_1       | 2024-07-09 20:05:55,510 - INFO - Waiting for application startup.
> secret_agent_1       | 2024-07-09 20:05:55,510 - INFO - Application startup complete.
> secret_agent_1       | 2024-07-09 20:06:00,241 - INFO - 127.0.0.1:33542 - "GET / HTTP/1.1" 200
> registration_task_1  | Traceback (most recent call last):
> registration_task_1  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
> registration_task_1  |     return _run_code(code, main_globals, None,
> registration_task_1  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
> registration_task_1  |     exec(code, run_globals)
> registration_task_1  |   File "/app/multi_agent_app/core_services/control_plane.py", line 41, in <module>
> registration_task_1  |     asyncio.run(register_and_start_consuming())
> registration_task_1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
> registration_task_1  |     return loop.run_until_complete(main)
> registration_task_1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
> registration_task_1  |     return future.result()
> registration_task_1  |   File "/app/multi_agent_app/core_services/control_plane.py", line 36, in register_and_start_consuming
> registration_task_1  |     start_consuming_callable = await control_plane.register_to_message_queue()
> registration_task_1  | AttributeError: 'ControlPlaneServer' object has no attribute 'register_to_message_queue'
> docker-kubernetes_registration_task_1 exited with code 1
>

**Comment by logan-markewich** [comment]
@pinyaras that method definitely exists on that class. Can you try updating? `pip install -U llama-agents`

**Comment by logan-markewich** [comment]
(Or I guess, ensure your docker is setup with a latest version)

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama-agents/blob/598574a8cd2401ae7ad35e0f0a7bd40627d4dc5a/llama_agents/control_plane/server.py#L384
