### ISSUE TITLE
openai.APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by ArmanTunga** [run-llama/llama_deploy#153]
I've encountered this error: `openai.APIConnectionError: Connection error.` while following Getting Started on repository's `README.md`. I used poetry to install the packages mentioned on Installation part in `README.md`.

After this part:
```
# launch it
launcher = LocalLauncher(
    [agent_server_1, agent_server_2],
    control_plane,
    message_queue,
)
result = launcher.launch_single("What is the secret fact?")

print(f"Result: {result}")
```
I get the error.

Partial Console log:
```
Retrying llama_index.llms.openai.base.OpenAI._achat in 0.8142595271750632 seconds as it raised APIConnectionError: Connection error..
Retrying llama_index.llms.openai.base.OpenAI._achat in 0.8624934507334412 seconds as it raised APIConnectionError: Connection error..
.
.
.
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```
While using llama-index I am not getting any errors like this, it works fine. I believe this issue is about async.

Full console log:
[full-console-log.txt](https://github.com/user-attachments/files/16323627/full-console-log.txt)

**Comment by nerdai** [comment]
Thanks @ArmanTunga for raising the issue. Have you set the `OPENAI_API_KEY` environment variable? I believe I've seen this before a few times... whenever I forget to supply my api key.

**Comment by ArmanTunga** [comment]
Thanks, the issue has been resolved! I've checked and I seem to have made a typo.

**Comment by ArmanTunga** [comment]
Thanks, the issue has been resolved! I've checked and I seem to have made a typo.

**Comment by nerdai** [comment]
> Thanks, the issue has been resolved! I've checked and I seem to have made a typo.

Dang typos! They get the best of us sometimes, for sure. Glad we got this one resolved!
