### ISSUE TITLE
Issues with orchestrator, fastapi and gemini-1.5-pro

### ISSUE THREAD

**Issue by jabbasj** [run-llama/llama_deploy#155]
I'm using Gemini-1.5-pro and running the code within a fastapi app

1. Orchestrator always returns to human after first agent response, I had to modify `llama_agents/orchestrators/agent.py line 107  response = await self.llm.apredict_and_call(tools_plus_human,...) to use only tools` to get it to work properly.
2. To get the thing to even run within fastapi, I had to comment out `llama_agents/launchers/local.py line 188 "signal.signal(signal.SIGINT, shutdown_handler)"` otherwise it would just crash
3. FunctionCallingAgentWorker says Gemini-1.5-pro doesn't support Function calling API yet ReActAgent works just fine with function calling (although I suspect it may be throwing off the Orchestrator)

**Comment by logan-markewich** [comment]
1. In general I'd advocate for people writing their own orchestrators. We have some changes upcoming that would make this easier to do
2. Are you running this inside an existing fast api server? The local launcher is meant to startup individual fastapi servers, and shouldn't be launched within an already running server 
3. Makes sense, react is not great. Only gemini over vertex supports function calling right now

**Comment by jabbasj** [comment]
> 1. In general I'd advocate for people writing their own orchestrators. We have some changes upcoming that would make this easier to do
> 2. Are you running this inside an existing fast api server? The local launcher is meant to startup individual fastapi servers, and shouldn't be launched within an already running server
> 3. Makes sense, react is not great. Only gemini over vertex supports function calling right now

Thanks for your response.

1. Fair enough, I'll look into creating my own orchestrator (any idea on ETA on those changes that make it easier?)
2. Yes, I'm running launch_single within an existing fastapi server.. I realize it is running its own fastapi server although there isn't any other launcher I can use -> perhaps I shouldn't be using this library in the first place and should just build my own multi-agent setup with llama-index? I was just trying to leverage the orchestration and message queues, etc.. (à la autogen groupchat)
3. What surprised me is that ReActAgent is able to use function calling with gemini-1.5-pro but FunctionCallingAgentWorker doesn't

**Comment by logan-markewich** [comment]
1. ETA 2 weeks ish? There's going to be some changes to llama-index-core, and that new abstraction will make its way over to llama-agents in a way that makes sense
2. I think the intention here would be to have llama-agents running separately from your existing fast-api server, and it interacts with the llama-agents system using a client 👀 I hope that makes sense 😅 There's maybe room to make LocalLauncher have more than just `launch_single()` and instead launch everything into the existing async loop perpetually 🤔 
3. React uses a prompting-based method to get the LLM to pick a tool. FunctionCallingAgentWorker relies on the LLM having some sort of tool calling built into the LLMs API (i.e. providing tools to OpenAI or anthropic requires no special prompting, its just a parameter in the api request)

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama-agents/issues/156

**Comment by logan-markewich** [comment]
We've done a major refactor, and I don't think this issue is relevant anymore
