### ISSUE TITLE
[feature req] Support for Agents from Other Frameworks

### ISSUE THREAD

**Issue by mahimairaja** [run-llama/llama_deploy#157]
The idea of hosting the agents as microservices is wonderful. Many of us work with multiple frameworks like llama-index, langchain, langgraph, crew ai to crew and deploy ai agents, it would be great if we could integrate them in to the game.

Looking forward to contribute for the same, Thanks

**Comment by logan-markewich** [comment]
We've done a major refactor, and I don't think this issue is relevant anymore (you can wrap any agent framework into a workflow and deploy that!)
