### ISSUE TITLE
Doesn't work in notebooks

### ISSUE THREAD

**Issue by tomaszbk** [run-llama/llama_deploy#162]
The docs says:
Next, when working in a **notebook** or for faster iteration, we can launch our llama-agents system in a single-run setting, where one message is propagated through the network and returned.
```
from llama_agents import LocalLauncher


# launch it
launcher = LocalLauncher(
    [agent_server_1, agent_server_2],
    control_plane,
    message_queue,
)
result = launcher.launch_single("What is the secret fact?")

print(f"Result: {result}")
```
But output is:
RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by nerdai** [comment]
hey @tomaszbk, you're probably running into a nested event loop problem? For notebooks, we need to use `nested_asyncio`. At the beginning of your noteboook add the following:

```python
import nest_asyncio

nest_asyncio.apply()
```

**Comment by tomaszbk** [comment]
Yes that fixed it! I think the docs should mention this because it seemed as if the code would just work out of the box when used in a notebook

**Comment by nerdai** [comment]
I agree @tomaszbk we should make mention of this in the docs! Sorry about the trouble. 

Do you want to submit a PR for it? Otherwise, I can do it -- up to you!

**Comment by tomaszbk** [comment]
I'll give it a try and create a PR! thanks!
