### ISSUE TITLE
Central state store

### ISSUE THREAD

**Issue by Achal1607** [run-llama/llama_deploy#172]
Langgraph offers a method for managing a central store, which is automatically passed to agents. These agents then utilize and update the state. Is it possible to implement a similar approach here, or does the architecture not support it?

Additionally, the documentation for llama-agents is not available in the llama index. If possible, could someone inform me when it will be released in llama-index-core?

**Comment by logan-markewich** [comment]
its going to continue to be a separate repo.

In fact, probably going to re-focus this repo as a way to deploy/scale workflows created in llama-index

As for your question about a state store, the control plane has a central kvstorage layer that will continue to be used as we make some refactors
