### ISSUE TITLE
Is it possible to implement a feature that allows for dynamic reloading of query engines and real-time updates to runtime configurations without restarting the entire service?

### ISSUE THREAD

**Issue by rohit-metrum-ai** [run-llama/llama_deploy#175]
Is there a way to dynamically reload query engines and update runtime configurations in Llama Agents without having to restart the entire service? This would be useful for applying changes to filters and settings in real-time without causing service interruptions.

**Comment by logan-markewich** [comment]
creating a query engine is basically a no-op, even more-so when backed by a remote vector store

If you had some custom service that loaded the index once, and then created the query engine for each request, that would be totally fine
