### ISSUE TITLE
[Question]: `llama-agents` vs Workflows?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_deploy#185]
[multi-agent-concierge](https://github.com/run-llama/multi-agent-concierge) describes itself as multi-agent but doesn't use `llama-agents`, instead just relying on the new workflow concept.

What is this project aiming to do that isn't redundant with workflows?

**Comment by logan-markewich** [comment]
@brycecf likely `llama-agents` will be rebranded to something like `llama-deploy` (see the various GitHub issues I've opened recently here for a peek at the changes coming)

Basically the idea is build stuff with llama-index, and then use the features here to deploy and scale. Want to make it as easy as possible to turn workflows into scalable services
