### ISSUE TITLE
`LookupError: Resource wordnet not found` when running Docker

### ISSUE THREAD

**Issue by ihsanKisi** [run-llama/llama_deploy#200]
I encountered an error when running the Docker container of the **human in the loop** example. The container exits with the following error message:

```
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/appuser/nltk_data'
    - '/app/.venv/nltk_data'
    - '/app/.venv/share/nltk_data'
    - '/app/.venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Steps to Reproduce:**
1. Clone the repository and navigate to the example directory.
2. Run the Docker container using the provided `docker-compose.yml` file.
3. The container exits with code 1, displaying the above error message.

**Actual Behavior:**
The container fails to find the `wordnet` resource and exits with an error.

**Environment:**
- **OS:** Windows 11 and Mac Sonoma 14
- **Docker Version:** 4.33.0

Thanks!

**Comment by logan-markewich** [comment]
We've done a major refactor, and I don't think this issue is relevant anymore
