### ISSUE TITLE
is there way to stop control plane Summarization , let me know if there is any best practice 

### ISSUE THREAD

**Issue by rohit-metrum-ai** [run-llama/llama_deploy#244]
my tool output is up to mark but control plane is Summarizing , i tried to do prompt engg but it is messing up my flow , let mw know if there is a way to stop control plane Summarization , thank you :)

**Comment by logan-markewich** [comment]
@Rohith-Scalers in the latest versions (i.e. with `llama-deploy` and the other refactors), the control plane is not doing any summarization 

Maybe take a peek at the latest readme to see how things have changed (the UX has changed quite a bit!)

**Comment by rohit-metrum-ai** [comment]
yaa , its working fine with latest update , thanks a lot :)
