### ISSUE TITLE
Add RabbitMQ as a message queue

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_deploy#25]
RabbitMQ is a popular message queue. For deployments and scalability, supporting it would be a huge win.

This may require tweaks to the message queue/publishing/consumer abstractions, but hopefully it fits nicely!

**Comment by jmiddleton** [comment]
RabbitMQ or any messaging system i.e. AWS SNS, Kafka or Azure Event Grid . I mean an abstraction of a queue where later we can have other providers as well.

**Comment by logan-markewich** [comment]
@jmiddleton We actually have a queue abstraction

https://github.com/run-llama/llama-agents/blob/main/llama_agents/message_queues/base.py

Whether or not this translates well to all queues, not sure yet :) But yes, would love to integrate with all those services above!
