### ISSUE TITLE
how can i pass output of one workflow to another workflow 

### ISSUE THREAD

**Issue by rohit-metrum-ai** [run-llama/llama_deploy#256]
is there a way to pass output of one workflow to another , right now my query need to call multiple workflow but after one running first workflow it is stoping

**Comment by logan-markewich** [comment]
Make a workflow that calls one or more sub-workflows

This section of the readme will be helpful
https://github.com/run-llama/llama_deploy?tab=readme-ov-file#deploying-nested-workflows

**Comment by rohit-metrum-ai** [comment]
Thank you logan i got the idea , but is there a way to have nested workflow structure based on prompt , just like how react agent works i found passing workflows as a functional tool to a react agent is working great but is there a way to do this in llama deploy inherently. Thank you :)

**Comment by logan-markewich** [comment]
I'm not sure what you mean by `is there a way to have nested workflow structure based on prompt` -- you might have to expand on that a bit more
