### ISSUE TITLE
Create Initial Docs

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_deploy#30]
A new docs site likely needs to be spun up. This should include at a minimum some basic installation, getting started, and a few guides.

Additionally, we need some API docs, which means writing a lot of docstrings (or getting copilot to help 😉)

**Comment by peteryxu** [comment]
would love to contribute to agent docs writing/generating, and site publishing. Let me know how I could get started. @logan-markewich

**Comment by logan-markewich** [comment]
@peteryxu while trying to avoid having too many docs sites, considering integrating the docs into llama-index docs.

I'm thinking the docs will mostly live in this repo, and the build step for the llama-index docs will clone this and copy over some info

Still need to try and get that working 😅

For docs in general, I'd really like to focus on a good quickstart (maybe the current readme isnt good enough), theory/structure overview, api docs (so good docstrings, since it's generated from that) and good examples.

**Comment by peteryxu** [comment]
that's sounds a good plan. I can start thinking about some good quickstarts, and arch overview.

**Comment by peteryxu** [comment]
For general DocOps automation & process, have you looked at https://www.komment.ai/#product ?  @logan-markewich

**Comment by masci** [comment]
Docs are now available at https://docs.llamaindex.ai/en/latest/module_guides/llama_deploy/ we can call this issue done, will open a new one in case later we want to have a dedicated website to serve Llama Deploy docs exclusively
