### ISSUE TITLE
llamactl deploy error  where deploy in remote serverapi

### ISSUE THREAD

**Issue by jdelacasa** [run-llama/llama_deploy#304]
clienthost$  llamactl -s http://serverapihost:4501 -t 20 deploy ./python_fullstack.yaml 
Error: Not Found

---------------------
serverapihost$  python -m llama_deploy.apiserver
INFO:     Started server process [988]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4501 (Press CTRL+C to quit)
INFO:     10.244.2.71:45480 - "POST /deployments/create HTTP/1.1" 404 Not Found

**Comment by masci** [comment]
Can you double check the version of llama_deploy you're using? `/deployments/create` was added later so my best guess would be you're running an earlier version.

**Comment by jdelacasa** [comment]
hi, dockerhub image : llamaindex/llama-deploy:v0.2.1
cliente llama-deploy==0.2.1

**Comment by masci** [comment]
I can't reproduce it, here is what I'm doing, from the root of the repo.
```
$ cd examples/quick_start
$ docker run -p 4501:4501 -v .:/opt/quickstart -w /opt/quickstart llamaindex/llama-deploy:v0.2.1
dadddad7b79b3d099afcaae132470e603dca82c32edbd7b1f68bebd5831d4b87
$ llamactl --version
llamactl, version 0.2.1
$ llamactl deploy ./quick_start.yml
Deployment successful: QuickStart
```
Can you try to do the same and let me know if it works?
