### ISSUE TITLE
StopEvent always retunrs a string

### ISSUE THREAD

**Issue by jdelacasa** [run-llama/llama_deploy#354]
My workflow running in a container:

.
.
return StopEvent(result={"response": response.response})

Querying the controlplane from another container:

client = httpx.AsyncClient()
apiserver_url = "http://dev-ng-controlplane:4501"
    
 payload = { "input": json.dumps(request_input), 
                "agent_id" : service_name
          }

response = await client.post(f"{apiserver_url}/deployments/{deployment_name}/tasks/run", 
                       json=payload, 
                       timeout=30)

print (type(response))
data = response.json()
print (type(data))

===== output

<class 'httpx.Response'>
<class 'str'>

**Comment by logan-markewich** [comment]
@jdelacasa correct -- it has to be serializeable, hence it gets thrown into json.dumps

You have to load it from there
