### ISSUE TITLE
"llamactl" is not recognized as an internal or external command, operable program, or batch file.

### ISSUE THREAD

**Issue by itxmarcos** [run-llama/llama_deploy#364]
llama-cloud==0.1.4
llama-index==0.11.23
llama-index-agent-openai==0.3.4
llama-index-cli==0.3.1
llama-index-core==0.11.23
llama-index-embeddings-openai==0.2.5
llama-index-indices-managed-llama-cloud==0.4.0
llama-index-legacy==0.9.48.post4
llama-index-llms-openai==0.2.16
llama-index-multi-modal-llms-openai==0.2.3
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.3.0
llama-index-readers-llama-parse==0.3.0
llama-parse==0.5.13

**Comment by masci** [comment]
@itxmarcos assuming that's the list of packages you have installed, I don't see `llama_deploy` that's the one shipping `llamactl`.
