### ISSUE TITLE
llama_deploy[rabbitmq] v 0.3.5 deploy_workflow not consume queue

### ISSUE THREAD

**Issue by volethanh** [run-llama/llama_deploy#393]
Hi

I got a problem that when run deploy workflow, the service not consume queue

When I push message by call api, the message request not forward to queue for workflow to handle

![IMG_7390](https://github.com/user-attachments/assets/3cfbfea4-154f-47e8-8cdb-00db0b8f9e5d)

![IMG_7391](https://github.com/user-attachments/assets/ee867ecc-d49f-4de5-8fcc-5068fab2eeb2)

**Comment by volethanh** [comment]
hello @masci , I’m currently stuck on this bug. When do you plan to check or fix it ?

**Comment by masci** [comment]
Hey @volethanh apologies for the delay here, I have a local test reproducing the problem, working on it right now I hope I can open a PR today!
