### ISSUE TITLE
Workflow State Session vs Task

### ISSUE THREAD

**Issue by masci** [run-llama/llama_deploy#401]
### Discussed in https://github.com/run-llama/llama_deploy/discussions/400

<div type='discussions-op-text'>

<sup>Originally posted by **Tehsmash** December 12, 2024</sup>
I've been playing around with llama deploy over the last couple of days and noticed a quirk and I don't know if it's a bug or intended behaviour.

When I issue two runs on the same session, it creates separate "tasks" for the session, but regardless of the input of the second task the output is always the same as the first session.run call. 

```
>>> session = client.create_session()
>>> result = session.run("assistant", input="what colour are bananas?")
>>> result
'{"response":"Bananas are typically yellow when they\'re ripe, but they can also be green or have other colors depending on the stage of ripeness and variety."}'
>>> result = session.run("assistant", input="how big is the sun?")
>>> result
'{"response":"Bananas are typically yellow when they\'re ripe, but they can also be green or have other colors depending on the stage of ripeness and variety."}'
```

Looking at the logs of my workflow, on the second run it doesn't even execute the steps in the workflow it just returns the final result straight away.

Debugging this, it seems like every task received by the WorkflowService saves the workflow state and context using the session_id, which means a few things:
1) it's not possible to have concurrent tasks within a session (global context is shared)
2) the state of a completed task (completed workflow run) gets reused for new tasks which seems to result in the workflow returning instantly. 

Can you confirm if there is a bug or misunderstanding here or not?</div>

**Comment by logan-markewich** [comment]
Hmm, i think part if this is a misunderstanding of sessions?

Sessions are meant to be sequential (since they share the same state). Think of use cases like a chatbot or some other iterative long-running workflow that needs to maintain context across runs

Now, is this made clear in the docs? Probably not. Especially since the client seems to encourage creating sessions before you can run a task.

**Comment by logan-markewich** [comment]
The issue on the reused result though is definitely a bug

**Comment by Tehsmash** [comment]
@logan-markewich that was one of my thoughts, i.e. was I misunderstanding sessions. Reusing the workflow context between runs is a little unexpected, I think those moving from non-deploy workflows to Llama deploy will not expect that behaviour. (Reusing context is a small advanced section in the workflow docs)
I certainly didn't expect it especially given you can run multiple session.run tasks in parallel.

In the case of a chat bot or something which needs to persist I have my own chat store + chat memory buffer for a particular workflow and simply pass the user + chat thread ID into the workflow run as an input. 

I can see the convenience of having a session store built into llama deploy but perhaps making it more explicit somehow like starting with a fresh context to avoid conflicts in the framework then injecting the session id and maybe even the task id into the context for use inside the workflow and have a client for session storage.

@masci It looks like the reuse of the result of the workflow is tied to how the workflow context is pickled in the workflow service. I've added a breakdown and code to recreate it to the original discussion.

**Comment by nerdai** [comment]
Going to close this now as the fix in framework has been merged.
