### ISSUE TITLE
llama deploy is not working

### ISSUE THREAD

**Issue by sreenivasanm6** [run-llama/llama_deploy#402]
Team, the provided example doesn't seem to work (esp with llama_deploy.apiserver). There is no create endpoint in the github here. Can you confirm and provide the right configuration details so as to run below example.
https://docs.llamaindex.ai/en/stable/module_guides/llama_deploy/10_getting_started/

**Comment by masci** [comment]
Hi @sreenivasanm6 the example from the docs runs just fine in a fresh virtual environement with llama-deploy==0.3.6 and llama-index-core==0.12.5. Moving this issue to discussions, it would be great if you could post the steps you're following and the errors you get, thanks!
