### ISSUE TITLE
Got another bug when run with rabbitmq at version 0.3.6

### ISSUE THREAD

**Issue by volethanh** [run-llama/llama_deploy#405]
Hi,

After you resolved the bug the workflow not consume queue and release v0.3.6. I have upgraded and when running I got this bug immediately 

![image](https://github.com/user-attachments/assets/9eb9020d-a11a-45b9-bac7-b5aa073d484a)

the length of list workflow_state_json is 0 so it cannot enter to the condition check is None. So it create loop infinite

**Comment by masci** [comment]
@volethanh do you have a snippet of code to reproduce?

**Comment by volethanh** [comment]
> @volethanh do you have a snippet of code to reproduce?

Just use the manual orchestration then I got that bug

**Comment by masci** [comment]
I can't reproduce, everything works as expected in the tests I've done and I'm going to close this unless you provide a working piece of code that gets stuck when using Rabbit as the message queue backend.

In case you're following exactly the code snippets from the docs, those were not clear and I reworded the whole page.
