### ISSUE TITLE
No `:latest` tag in DockerHub

### ISSUE THREAD

**Issue by rtreddick** [run-llama/llama_deploy#415]
In Getting Started (https://docs.llamaindex.ai/en/latest/module_guides/llama_deploy/10_getting_started/), there are instructions for running the API server on Docker:

`$ docker run -p 4501:4501 -v .:/opt/quickstart -w /opt/quickstart llamaindex/llama-deploy`

This tries to pull the `:latest` tag, but there is no latest tag in DockerHub.

![image](https://github.com/user-attachments/assets/e3f9d82e-99e5-4136-90b5-7dfd23f80610)

<img width="810" alt="image" src="https://github.com/user-attachments/assets/2e802637-1994-4baf-96a2-b6abfd14039d" />

Can we add a `:latest` tag or update the docs to specify the `:main` tag.

**Comment by masci** [comment]
We don't provide the `latest` tag by design, I'll update the docs thanks for opening this issue!
