### ISSUE TITLE
Bug Report: API endpoints `/docs` and `/status` return 404 Not Found

### ISSUE THREAD

**Issue by limaolin2017** [run-llama/llama_deploy#418]
### Description
When deploying the API server using `python -m llama_deploy.apiserver`, the server starts successfully but both `/docs` and `/status` endpoints return 404 Not Found errors. The root path `/` is accessible but returns no content.

### Steps to Reproduce
1. Install llama-deploy (tested with v0.3.0 and v0.3.6)
2. Run `python -m llama_deploy.apiserver`
3. Server starts successfully on `http://0.0.0.0:4501`
4. Try to access:
   - `http://localhost:4501/docs` -> Returns 404
   - `http://localhost:4501/status` -> Returns 404
   - `http://localhost:4501/` -> Accessible but empty response

### Expected Behavior
- `/docs` should show the Swagger UI documentation
- `/status` should return the server status
- `/` should return valid content

### Actual Behavior
- `/docs` returns `{"detail":"Not Found"}`
- `/status` returns `{"detail":"Not Found"}`
- `/` returns no content

### Environment
- llama-deploy versions tested: v0.3.0, v0.3.6
- Python version: 3.10
- OS: Linux
- FastAPI and uvicorn are working correctly (verified with test file)

### Additional Context
- The basic FastAPI setup works fine (tested with a simple test file)
- This appears to be an issue with the llama-deploy framework itself
- The problem exists in both recent versions (v0.3.0 and v0.3.6)

### Verification
Created a test FastAPI application to verify that the base FastAPI/uvicorn setup works correctly, confirming this is a framework-specific issue rather than an environment problem.

**Comment by masci** [comment]
I can't reproduce on my end, I tried both the `main` branch and the tag `v0.3.6`. By accessing `/status` or `/docs` I get a 307 redirect to `/status/` and `/docs/` respectively, but then I can see the right content, I wasn't able to trigger a 404. Can you double check you don't have a different uvicorn application listening to port 4501? You can run the following command from a shell:
```
sudo netstat -nlp | grep :4501
```
and see the PID of the process listening on the port, then double check that's actually `python -m llama_deploy.apiserver`.

**Comment by limaolin2017** [comment]
I found the issue—it was a conflict between llama_deploy and DSPy. I resolved it by downgrading the version of python-multipart to 0.0.18 using `pip install python-multipart==0.0.18`. I will close this now, thank you for your help.
