### ISSUE TITLE
More efficient task processing

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_deploy#42]
Right now, the agent and tools services process one task at a time

This means the processing loop is blocked by the time it takes to execute the single step of task

We can probably make this more efficient 

For agents
- processing a step in the background (i.e. create_task() ?)
- add a callback to handle the case where a task is done and a response should be published

For tools
- most tools probably won't be async
- should we be threading? Or take the same approach as above

**Comment by jianhuanggo** [comment]
how many concurrent agents we plan to support?
