### ISSUE TITLE
Make Services state-less

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_deploy#48]
Currently, the services carry a lot of state

Similar to the control plane, we should be able to abstract away the state into some shared kv-store, so that individual services can be horizontally scalable in the future!

**Comment by nerdai** [comment]
Sounds good to me! I didn't realize that we had this pattern already implemented for control plane.

**Comment by logan-markewich** [comment]
heh, I kind of snuck it in 😉 the kvstore in llama-index is super handy for this

**Comment by logan-markewich** [comment]
This is technically not need. Why?
- A task cannot be assigned to more than one replica of an agent service 
- Therefore, the states for tasks will not collide if horizontally scaled
