### ISSUE TITLE
Add YAML definition for components

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_deploy#67]
It would be really nice to be able to define the entire system from YAML

Each of these components would need a yaml def, and a function to load from yaml
- AgentService
- ToolService
- HumanService
- ControlPlaneServer
- SimpleMessageQueue
- etc.

Ideally, we can support custom code by linking to an import path/module that is dynamically loaded? (Although not sure if this is a security risk)

**Comment by nickknyc** [comment]
Yes, please!

**Comment by masci** [comment]
This is fundamentally done, see https://docs.llamaindex.ai/en/stable/module_guides/llama_deploy/20_core_components/#deployment
