### ISSUE TITLE
🎉 Congrats for the launch!

### ISSUE THREAD

**Issue by enricoros** [run-llama/llama_deploy#69]
Congrats to the team for the launch today! (just a praise ticket, this can be closed) 
Love the idea and the architecture (would love some docs on the protocols), and wish the greatest success to this project.
🦙♡🤖

**Comment by logan-markewich** [comment]
Thanks @enricoros ! Better docs are coming soon! 

Since each service/control plane/message queue is also a fastapi server, it will generate API docs if you visit `http://host:port/docs`
