### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.agent'

### ISSUE THREAD

**Issue by deboboy** [run-llama/llama_deploy#72]
**Running the example from the announcement blog post:**
https://www.llamaindex.ai/blog/introducing-llama-agents-a-powerful-framework-for-building-production-multi-agent-ai-systems

**Tried to run at this step:**
`# Set up the launcher for local testing
from llama_agents import LocalLauncher

launcher = LocalLauncher(
    [agent_service],
    control_plane,
    message_queue,
)

Run a single query through the system
result = launcher.launch_single("What's the secret fact?")
print(result)`

**Getting this error:**
`from llama_index.agent.openai.utils import resolve_tool_choice
ModuleNotFoundError: No module named 'llama_index.agent'`

**Comment by logan-markewich** [comment]
@deboboy apologies, that assumes you had llama-index already installed. Try `pip install llama-index-agent-openai`

**Comment by logan-markewich** [comment]
Updated the readme to reflect this
