### ISSUE TITLE
how to use ollama api?

### ISSUE THREAD

**Issue by win4r** [run-llama/llama_deploy#75]
how to use ollama api?

**Comment by anoopshrma** [comment]
~~I don't think you can use this with Ollama as Agent requires llm of type `FunctionCallingLLM`  which ollama is not.~~

Edit: Refer to below provided way

**Comment by win4r** [comment]
what about Gemma2?

**Comment by ravi03071991** [comment]
Hey @win4r ,

You can use any LLM with `ReAct` agent. Here is a sample code snippet:

```python
from llama_index.llms.ollama import Ollama

ollama_llm = Ollama(model="gemma2", request_timeout=120.0)

tool = FunctionTool.from_defaults(fn=<function>)

agent1 = ReActAgent.from_tools([tool], llm=ollama_llm)
agent2 = ReActAgent.from_tools([], llm=ollama_llm)
```

**Comment by logan-markewich** [comment]
Exactly as above! You can use any llm integration from llama-index. Just make sure you install it `pip install llama-index-llms-openai`

but note that open-source LLMs are still quite behind in terms of agentic reasoning. I would recommend keeping things as simple as possible. Even for the orchestrator, I would use a pipeline orchestrator, or even try defining a custom one. (Working on a custom example soon! The base class is very simple)

**Comment by win4r** [comment]
> Hey @win4r ,
> 
> You can use any LLM with `ReAct` agent. Here is a sample code snippet:
> 
> ```python
> from llama_index.llms.ollama import Ollama
> 
> ollama_llm = Ollama(model="gemma2", request_timeout=120.0)
> 
> tool = FunctionTool.from_defaults(fn=<function>)
> 
> agent1 = ReActAgent.from_tools([tool], llm=ollama_llm)
> agent2 = ReActAgent.from_tools([], llm=ollama_llm)
> ```

ValueError: Model name gemma2 does not support function calling API.

**Comment by logan-markewich** [comment]
@win4r that code does not produce that error. Are you sure you used a react agent?
