### ISSUE TITLE
2 tons of examples, assertions and lack of information

### ISSUE THREAD

**Issue by techserv01** [run-llama/llama_deploy#89]

**Comment by logan-markewich** [comment]
@techserv01 there are tons of examples of more complex RAG in llama-index

I found at least two examples of semantic chunking in llama-index
https://docs.llamaindex.ai/en/stable/examples/node_parsers/semantic_double_merging_chunking/?h=semantic
https://docs.llamaindex.ai/en/stable/examples/node_parsers/semantic_chunking/?h=semantic

The idea with example notebooks in this repo is to show you how to setup/use a systems and abstractions from this repo, as there are a lot of concepts without throwing more RAG details into the mix.

Also, IMO the semantic parser is largely experimental 😅

**Comment by techserv01** [comment]
Good day and thank you!

I would appreciate an expansion on the comment that the semantic parser is "largely experimental". I used the windowed sentence parser but felt like a larger but smarter chunking implementation should be used.

I am not particularly concerned with where the code is stored. It sounds like this repo is not the right place. 

Again, it's not just semantic parsing -- which you have provided pointers to -- but other RAG optimizations and techniques that would be nice to have as a single example. 

thank you very much for the assistance!

**Comment by logan-markewich** [comment]
I guess what I'm saying is, there are endless ways to optimize RAG, and llama-index has tons of examples for that. 

If want to see more, explore the examples there 💪🏻 From there, its just a matter of attaching your RAG pipeline to an agent 👍🏻
