### ISSUE TITLE
Installation Instruction missing one pip library

### ISSUE THREAD

**Issue by peteryxu** [run-llama/llama_deploy#92]
started from scratch, cloned this repo, created an venv,  and followed instruction doc below:
pip install llama-agents
#if you don't already have llama-index installed, to follow these examples, you'll also need
pip install llama-index-agent-openai

When running agentic_local_single.py, still get error below:
ImportError: `llama-index-embeddings-openai` package not found, please run `pip install llama-index-embeddings-openai`

The Installation section of Readme.md should include the following: 
pip install llama-index-embeddings-openai

**Comment by logan-markewich** [comment]
fair enough, llama-index is defaulting to openai embeddings

Related to #87 this should be more lazily initialized I think

**Comment by peteryxu** [comment]
closed as fixed in PR#106
